import type { SupabaseClient } from "@supabase/supabase-js";

import { supabaseAdmin } from "@/integrations/supabase/client.server";

/**
 * Untyped admin client. The generated `Database` types are regenerated by the
 * platform migration workflow, which this project does not use (the app runs on
 * a personal Supabase project), so schema changes such as `facts.pick_date`
 * are not reflected there. Queries go through this loose client instead.
 */
export const dbAdmin = supabaseAdmin as unknown as SupabaseClient;
